<meta property="og:title" content="<?php echo FacebookHelper::getTitle();?>"/>
<meta property="og:description" content="<?php echo FacebookHelper::getDescription();?>"/>
<meta property="og:url" content="<?php echo FacebookHelper::getUrl();?>"/>
<meta property="og:image" content="<?php echo FacebookHelper::getImage();?>"/>
<meta property="og:type" content="<?php echo FacebookHelper::getType();?>"/>
<meta property="og:site_name" content="<?php echo $_SERVER['SERVER_NAME'];?>"/>
<meta property="fb:admins" content="<?php echo FacebookHelper::getAppAdmins();?>"/>
<meta property="fb:app_id" content="<?php echo FacebookHelper::getAppID();?>"/>

